/*
//Error Handling
try{
    console.log("This is try block");
    console.log(x);
    console.log("try block ends here")
}
catch(e){
    console.log("This is catch block");
    console.log("Your error is here", e);
}
finally{
    console.log("Always execute")
}

// create custom error
try{
    console.log(x);//reference error
}
catch(e){
    throw new Error("Please Declared first and print");
}
*/
